### ISSUE TITLE
Error_C1M6L2_Final_Project_V3

### ISSUE THREAD

**Issue by thedarshanjadhav** [PiyushKhanna30/Word-Cloud#2]
Getting error in 'Display your wordcloud image'
name 'file_contents' is not defined
I checked many times whole code but again and again i'm getting the same error

**Comment by PiyushKhanna30** [comment]
https://github.com/PiyushKhanna30/Word-Cloud/commit/c9cf867c153c2f2ededb03eb6408a757c796bcbd#commitcomment-39230268

**Comment by thedarshanjadhav** [comment]
Sir I'm not getting any type of file upload option.. can u plss elaborate how can i complete this assignment
